/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inc.cygnus.view;

import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TA planning
 */
public class Menu extends javax.swing.JFrame {

    private CustomerListForm customerList;
    private ProductListForm productList;
    private final List<String> listInternalFrame = new ArrayList<String>();
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemCustomer = new javax.swing.JMenuItem();
        menuItemProduct = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemPurchase = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Menu");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Master");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Customer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Product");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Transaction");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Purchase");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Laundry");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Report");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Day");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Month");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Year");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree1);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jDesktopPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jDesktopPane1);

        jMenu1.setText("File");

        menuItemCustomer.setText("Customer");
        menuItemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCustomerActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCustomer);

        menuItemProduct.setText("Product");
        menuItemProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProductActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemProduct);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Transaction");

        menuItemPurchase.setText("Purchase");
        menuItemPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPurchaseActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemPurchase);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCustomerActionPerformed
        if (customerList == null) {
            customerList = new CustomerListForm();
            jDesktopPane1.add(customerList, MAXIMIZED_BOTH);
            
            customerList.setVisible(true);
            customerList.setBorder(null);
            customerList.setVisible(true);
            customerList.setMaximizable(true);
            customerList.setSize(jDesktopPane1.getSize());
            try {
                customerList.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            ((javax.swing.plaf.basic.BasicInternalFrameUI)customerList.getUI()).setNorthPane(null);
            listInternalFrame.add("customerList");
        } else {
            try {
                customerList.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuItemCustomerActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (!listInternalFrame.isEmpty()) {
            for (String s : listInternalFrame) {
                switch (s) {
                    case "customerList":
                        if (customerList != null) {
                            customerList.setSize(jDesktopPane1.getSize());
                        }   break;
                    case "productList":
                        if (productList != null) {
                            productList.setSize(jDesktopPane1.getSize());
                        }   break;
                }
            }
        }

    }//GEN-LAST:event_formComponentResized

    private void menuItemProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProductActionPerformed
        if (productList == null) {
            productList = new ProductListForm();
            jDesktopPane1.add(productList, MAXIMIZED_BOTH);
            
            productList.setVisible(true);
            productList.setBorder(null);
            productList.setVisible(true);
            productList.setMaximizable(true);
            productList.setSize(jDesktopPane1.getSize());
            try {
                productList.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            ((javax.swing.plaf.basic.BasicInternalFrameUI)productList.getUI()).setNorthPane(null);
            listInternalFrame.add("productList");
        } else {
            try {
                productList.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuItemProductActionPerformed

    private void menuItemPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPurchaseActionPerformed
        PurchaseEntryForm p = null;
        if (p == null) {
            p = new PurchaseEntryForm();
            productList.setVisible(true);
        } else {
            productList.setVisible(true);
        }
    }//GEN-LAST:event_menuItemPurchaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem menuItemCustomer;
    private javax.swing.JMenuItem menuItemProduct;
    private javax.swing.JMenuItem menuItemPurchase;
    // End of variables declaration//GEN-END:variables
}
