/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inc.cygnus.view;

import inc.cygnus.app.MainSpring;
import inc.cygnus.model.Product;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author TA planning
 */
public class ProductListForm extends javax.swing.JInternalFrame {

    private List<Product> listProduct;
    private final ProductTableModel productTableModel = new ProductTableModel(null);
    
    /**
     * Creates new form ProductListForm
     */
    public ProductListForm() {
        initComponents();
        findAllData();
    }

    private void findAllData() {
        listProduct = MainSpring.getProductService().findAllData("", "", 0, 20);
        try {
            if (!listProduct.isEmpty()) {
                
                for (Product p : listProduct) {
                    System.err.println("Nama: " + p.getName() + ", " 
                            + p.getUnit() + ", " + p.getId() + ", " + p.getUnitPrice());
                }
                
                productTableModel.setTableModel(listProduct);
                tblProduct.setModel(productTableModel);
            }
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    

    }
    
    /**
     * Abstract Tabel Model Product
     */
    private class ProductTableModel extends AbstractTableModel {

        private List<Product> listProduct;

        public ProductTableModel(List<Product> listProduct) {
            this.listProduct = listProduct;
        }

        public void setTableModel(List<Product> listProduct) {
            this.listProduct = listProduct;
        }

        @Override
        public int getRowCount() {
            return listProduct.size();
        }

        @Override
        public int getColumnCount() {
            return 6;
        }

        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:
                    return "ID";
                case 1:
                    return "Name";
                case 2:
                    return "Addres";
                case 3:
                    return "Contact";
                default:
                    return "";
            }
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Product s = listProduct.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return s.getId();
                case 1:
                    return s.getName();
                case 2:
                    return s.getUnit();
                case 3:
                    return s.getUnitPrice();
                case 4:
                    return s.getDateCreated();
                case 5:
                    return s.getDateModified();
                default:
                    return "";
            }
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            @SuppressWarnings("unchecked")
            Class<ProductTableModel>[] columnTypes = new Class[] {
                Long.class, String.class, String.class, BigDecimal.class,  Date.class, Date.class //, String.class
            };
        
            return columnTypes[columnIndex];
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            /*if (columnIndex == 3) {
                return true;
            }*/
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            Product s = listProduct.get(rowIndex);
            /*if (columnIndex == 3) {
                //	            s.setQuantity((Integer) aValue);
                //	            s.setSubtotal(s.getPrice().multiply(
                //	                    new BigDecimal(s.getQuantity())));
                //	            refreshTotalLabel();
            }*/
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnAddNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPrint = new javax.swing.JButton();

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(tblProduct);

        jToolBar1.setRollover(true);

        btnAddNew.setText("Add New");
        btnAddNew.setFocusable(false);
        btnAddNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddNew);

        btnEdit.setText("Edit");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEdit);
        jToolBar1.add(jSeparator1);

        btnPrint.setText("Print All");
        btnPrint.setFocusable(false);
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        ProductEntryForm p = new ProductEntryForm(null, true);
        p.setVisible(true);
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables
}
